### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by ElliotKetchup** [VazkiiMods/AutoRegLib#41]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2020-05-15 12:13:34 CEST
Description: Initializing game

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
    at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
    at vazkii.arl.util.ProxyRegistry.onRegistryEvent(ProxyRegistry.java:85)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_403_ProxyRegistry_onRegistryEvent_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1700493632 bytes (1621 MB) / 4187488256 bytes (3993 MB) up to 6692536320 bytes (6382 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7180m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 147 mods loaded, 147 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                     | Version                   | Source                                                    | Signature                                |
       |:----- |:---------------------- |:------------------------- |:--------------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft              | 1.12.2                    | minecraft.jar                                             | None                                     |
       | LCH   | mcp                    | 9.42                      | minecraft.jar                                             | None                                     |
       | LCH   | FML                    | 8.0.99.99                 | forge-1.12.2-14.23.5.2854.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                  | 14.23.5.2854              | forge-1.12.2-14.23.5.2854.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | ivtoolkit              | 1.3.3-1.12                | minecraft.jar                                             | None                                     |
       | LCH   | movillages             | 1.5.4                     | [1.12]MoVillages-1.5.4.jar                                | None                                     |
       | LCH   | jei                    | 4.15.0.291                | jei_1.12.2-4.15.0.291.jar                                 | None                                     |
       | LCH   | abyssalcraft           | 1.9.19.1                  | AbyssalCraft-1.12.2-1.9.19.1.jar                          | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCH   | actuallyadditions      | 1.12.2-r151               | ActuallyAdditions-1.12.2-r151-2.jar                       | None                                     |
       | LCH   | baubles                | 1.5.2                     | Baubles-1.12-1.5.2.jar                                    | None                                     |
       | LCH   | actuallybaubles        | 1.1                       | ActuallyBaubles-1.12-1.1.jar                              | None                                     |
       | LCH   | forgeendertech         | 1.12.2-4.5.2.0            | ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar              | None                                     |
       | LCH   | adlods                 | 1.12.2-1.0.7.1            | AdLods-1.12.2-1.0.7.1-build.0441.jar                      | None                                     |
       | LCH   | aether_legacy          | 1.4.4                     | aether_legacy-1.12.2-v1.4.4.jar                           | None                                     |
       | LCH   | aether_legacy_addon    | 1.12.2-v1.2.3             | aether_continuation-1.12.2-v1.2.3.jar                     | None                                     |
       | LCH   | infinitylib            | 1.12.2-1.12.0             | infinitylib-1.12.0_oc_patch.jar                           | None                                     |
       | LCH   | agricraft              | 2.12.0-1.12.0-a6          | AgriCraft-2.12.0-1.12.0-a6.jar                            | None                                     |
       | LCH   | akashictome            | 1.2-12                    | AkashicTome-1.2-12.jar                                    | None                                     |
       | LCH   | animalium              | 0.3.8                     | Animalium-0.3.8.jar                                       | None                                     |
       | LCH   | craftstudioapi         | 1.0.0                     | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar        | None                                     |
       | LCH   | ctm                    | MC1.12.2-1.0.2.31         | CTM-MC1.12.2-1.0.2.31.jar                                 | None                                     |
       | LCH   | twilightforest         | 3.10.1013                 | twilightforest-1.12.2-3.10.1013-universal.jar             | None                                     |
       | LCH   | animania               | 1.7.3                     | animania-1.12.2-1.7.3.jar                                 | None                                     |
       | LCH   | cyclicmagic            | 1.20.2                    | Cyclic-1.12.2-1.20.2.jar                                  | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
       | LCH   | guideapi               | 1.12-2.1.8-63             | Guide-API-1.12-2.1.8-63.jar                               | None                                     |
       | LCH   | bloodmagic             | 1.12.2-2.4.3-105          | BloodMagic-1.12.2-2.4.3-105.jar                           | None                                     |
       | LCH   | animus                 | 1                         | Animus-1.12-2.1.7.jar                                     | None                                     |
       | LCH   | aoa3                   | 3.2.7                     | AoA3-3.2.7.jar                                            | 8bddeac148843f40e0b9f69201be2f4b3071700d |
       | LCH   | aqua_creepers          | 1.2.3                     | AquaCreepers-1.2.3.jar                                    | None                                     |
       | LCH   | aquaculture            | 1.6.8                     | Aquaculture-1.12.2-1.6.8.jar                              | None                                     |
       | LCH   | mantle                 | 1.12-1.3.3.55             | Mantle-1.12-1.3.3.55.jar                                  | None                                     |
       | LCH   | roots                  | 1.12.2-3.0.28             | Roots-1.12.2-3.0.28.jar                                   | None                                     |
       | LCH   | mysticalworld          | 1.12.2-1.8.4              | mysticalworld-1.12.2-1.8.4.jar                            | None                                     |
       | LCH   | chisel                 | MC1.12.2-1.0.2.45         | Chisel-MC1.12.2-1.0.2.45.jar                              | None                                     |
       | LCH   | tombstone              | 3.7.3                     | tombstone-3.7.3-1.12.2.jar                                | None                                     |
       | LCH   | quark                  | r1.6-179                  | Quark-r1.6-179.jar                                        | None                                     |
       | LCH   | tconstruct             | 1.12.2-2.13.0.183         | TConstruct-1.12.2-2.13.0.183.jar                          | None                                     |
       | LCH   | thedragonlib           | 1.12.2-5.3.0              | thedragonlib-1.12.2-5.3.0.jar                             | None                                     |
       | LCH   | armorplus              | 1.12.2-11.28.0.69         | armorplus-1.12.2-11.28.0.69.jar                           | None                                     |
       | LCH   | astralsorcery          | 1.10.22                   | astralsorcery-1.12.2-1.10.23.jar                          | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | LCH   | atum                   | 2.0.17                    | Atum-1.12.2-2.0.17.jar                                    | None                                     |
       | LCH   | autoreglib             | 1.3-32                    | AutoRegLib-1.3-32.jar                                     | None                                     |
       | LCH   | forestry               | 5.8.2.387                 | forestry_1.12.2-5.8.2.387.jar                             | None                                     |
       | LCH   | binniecore             | 2.5.1.203                 | binnie-mods-1.12.2-2.5.1.203.jar                          | None                                     |
       | LCH   | binniedesign           | 2.5.1.203                 | binnie-mods-1.12.2-2.5.1.203.jar                          | None                                     |
       | LCH   | genetics               | 2.5.1.203                 | binnie-mods-1.12.2-2.5.1.203.jar                          | None                                     |
       | LCH   | botany                 | 2.5.1.203                 | binnie-mods-1.12.2-2.5.1.203.jar                          | None                                     |
       | LCH   | extrabees              | 2.5.1.203                 | binnie-mods-1.12.2-2.5.1.203.jar                          | None                                     |
       | LCH   | extratrees             | 2.5.1.203                 | binnie-mods-1.12.2-2.5.1.203.jar                          | None                                     |
       | LCH   | conarm                 | 1.2.5.4                   | conarm-1.12.2-1.2.5.4.jar                                 | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCH   | bloodtinker            | 1.0.5                     | bloodtinker-1.0.5.jar                                     | None                                     |
       | LCH   | bonsaitrees            | 1.1.4                     | bonsaitrees-1.1.4-b170.jar                                | None                                     |
       | LCH   | bookshelf              | 2.3.585                   | Bookshelf-1.12.2-2.3.585.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | chameleon              | 1.12-4.1.3                | Chameleon-1.12-4.1.3.jar                                  | None                                     |
       | LCH   | clumps                 | 3.1.2                     | Clumps-3.1.2.jar                                          | None                                     |
       | LCH   | coherentvillages       | v0.0.5.10                 | coherent_villages-pre-release_v0.0.5.10.jar               | None                                     |
       | LCH   | cyclopscore            | 1.6.4                     | CyclopsCore-1.12.2-1.6.4.jar                              | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | colossalchests         | 1.7.3                     | ColossalChests-1.12.2-1.7.3.jar                           | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | cookingforblockheads   | 6.5.0                     | CookingForBlockheads_1.12.2-6.5.0.jar                     | None                                     |
       | LCH   | cucumber               | 1.1.3                     | Cucumber-1.12.2-1.1.3.jar                                 | None                                     |
       | LCH   | doggytalents           | 1.15.1.5                  | DoggyTalents-1.12.2-1.15.1.5.jar                          | None                                     |
       | LCH   | dldungeonsjbg          | 1.13.2                    | DoomlikeDungeons-1.13.2-MC1.12.2.jar                      | None                                     |
       | LCH   | mocreatures            | 12.0.5                    | DrZharks+MoCreatures+Mod-12.0.5.jar                       | None                                     |
       | LCH   | dungeonmobs            | 5.8.5                     | dungeonmobs-5.8.5-MC1.12.2.jar                            | None                                     |
       | LCH   | dungeontactics         | DT-0.16.6                 | DungeonTactics-1.12.2-0.16.6.jar                          | None                                     |
       | LCH   | orelib                 | 3.6.0.1                   | OreLib-1.12.2-3.6.0.1.jar                                 | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | dsurround              | 3.6.1.0                   | DynamicSurroundings-1.12.2-3.6.1.0.jar                    | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | ebwizardry             | 4.2.11                    | ElectroblobsWizardry-4.2.11-MC1.12.2.jar                  | None                                     |
       | LCH   | endercrop              | 1.12.2-1.6.0              | endercrop-1.12.2-1.6.0.jar                                | None                                     |
       | LCH   | exoticbirds            | 1.0                       | Exotic+Birds+1.12.2-3.1.0.jar                             | None                                     |
       | LCH   | moa_dlc                | v1.2.0                    | extra-moas-v1.2.0.jar                                     | None                                     |
       | LCH   | extragems              | 1.2.8                     | ExtraGems-1.12.2-(v.1.2.8).jar                            | None                                     |
       | LCH   | extrautils2            | 1.0                       | extrautils2-1.12-1.9.9.jar                                | None                                     |
       | LCH   | familiarfauna          | 1.0.11                    | FamiliarFauna-1.12.2-1.0.11.jar                           | None                                     |
       | LCH   | farlanders             | 1.0.1                     | farlanders-1.12.2-1.0.1.jar                               | None                                     |
       | LCH   | farmingforblockheads   | 3.1.28                    | FarmingForBlockheads_1.12.2-3.1.28.jar                    | None                                     |
       | LCH   | fastfurnace            | 1.3.1                     | FastFurnace-1.12.2-1.3.1.jar                              | None                                     |
       | LCH   | giacomosfoundry        | 1.3.13                    | GiacomosFoundry-1.12.2-1.3.13.jar                         | None                                     |
       | LCH   | huntingdim             | 1.0.42                    | HuntingDimension-1.12.2-1.0.42.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | llibrary               | 1.7.19                    | llibrary-1.7.19-1.12.2.jar                                | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCH   | iceandfire             | 1.9.1                     | iceandfire-1.9.1-1.12.2.jar                               | None                                     |
       | LCH   | illagers_plus          | 1.1                       | IllagersPlus-1.12.2-1.1.3.jar                             | None                                     |
       | LCH   | inventorypets          | 2.0.5                     | inventorypets-1.12-2.0.5.jar                              | None                                     |
       | LCH   | ironchest              | 1.12.2-7.0.67.844         | ironchest-1.12.2-7.0.72.847.jar                           | None                                     |
       | LCH   | ironfurnaces           | 1.3.5                     | ironfurnaces-1.3.5.jar                                    | None                                     |
       | LCH   | journeymap             | 1.12.2-5.7.1              | journeymap-1.12.2-5.7.1.jar                               | None                                     |
       | LCH   | jaff                   | 1.7_for_1.12              | JustAFewFish-1.7_for_1.12.jar                             | None                                     |
       | LCH   | justenoughdimensions   | 1.6.0-dev.20200416.184714 | justenoughdimensions-1.12.2-1.6.0-dev.20200416.184714.jar | 2b03e1423915a189b8094816baa18f239d576dff |
       | LCH   | libraryex              | 1.1.3                     | LibraryEx-1.12.2-1.1.3.jar                                | None                                     |
       | LCH   | lost_aether            | 0.1.3                     | lost_aether-content-1.12.2-0.1.3.jar                      | None                                     |
       | LCH   | magicbees              | 1.0                       | MagicBees-1.12.2-3.1.10.jar                               | None                                     |
       | LCH   | mysticalagriculture    | 1.7.5                     | MysticalAgriculture-1.12.2-1.7.5.jar                      | None                                     |
       | LCH   | matc                   | 1.0.1-hotfix              | matc-1.0.1-hotfix.jar                                     | None                                     |
       | LCH   | moartinkers            | 0.6.0                     | moartinkers-0.6.0.jar                                     | None                                     |
       | LCH   | mo_swords              | v5                        | moSwords-1.12.2v5.jar                                     | None                                     |
       | LCH   | mousetweaks            | 2.10                      | MouseTweaks-2.10-mc1.12.2.jar                             | None                                     |
       | LCH   | mowziesmobs            | 1.5.4                     | mowziesmobs-1.5.4.jar                                     | None                                     |
       | LCH   | multimob               | 1.0.5                     | multimob-1.0.5.jar                                        | None                                     |
       | LCH   | mysticalagradditions   | 1.3.2                     | MysticalAgradditions-1.12.2-1.3.2.jar                     | None                                     |
       | LCH   | netherex               | 2.1.5                     | NetherEx-1.12.2-2.1.6.jar                                 | None                                     |
       | LCH   | oreexcavation          | 1.4.150                   | OreExcavation-1.4.150.jar                                 | None                                     |
       | LCH   | patchouli              | 1.0-20                    | Patchouli-1.0-20.jar                                      | None                                     |
       | LCH   | potionfingers          | r1.0-2                    | PotionFingers-r1.0-2.jar                                  | None                                     |
       | LCH   | prefab                 | 1.3.0.26                  | prefab-1.3.0.26.jar                                       | None                                     |
       | LCH   | primitivemobs          | 1.2.3a                    | primitivemobs-1.2.3a.jar                                  | None                                     |
       | LCH   | quarkoddities          | 1                         | QuarkOddities-1.12.2.jar                                  | None                                     |
       | LCH   | randomloot             | 1.7.3                     | randomloot+1.7.4.jar                                      | None                                     |
       | LCH   | reap                   | 1.5.2                     | reap-1.5.2.jar                                            | None                                     |
       | LCH   | reccomplex             | 1.4.8.2                   | RecurrentComplex-1.4.8.2.jar                              | None                                     |
       | LCH   | reptilemod             | 3.8.4                     | reptilemod-1.12.2-3.8.4-89.jar                            | None                                     |
       | LCH   | additionalstructures   | 2.3.1                     | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar          | None                                     |
       | LCH   | roguelike              | 1.8.0                     | RoguelikeDungeons-1.12.2-1.8.0.jar                        | None                                     |
       | LCH   | rustic                 | 1.1.3                     | rustic-1.1.3.jar                                          | None                                     |
       | LCH   | shipwrecks_winslow     | 2.0.0                     | shipwrecks-mc1.12.2-2.0.0.jar                             | None                                     |
       | LCH   | storagenetwork         | 1.7.10                    | SimpleStorageNetwork-1.12.2-1.7.10.jar                    | None                                     |
       | LCH   | skewers                | 1.1                       | Skewers-1.1.jar                                           | None                                     |
       | LCH   | spartanweaponry        | beta 1.3.8                | SpartanWeaponry-1.12.2-beta-1.3.8.jar                     | None                                     |
       | LCH   | spartancompat          | @VERSION@                 | spartancompat-1.2.2.jar                                   | None                                     |
       | LCH   | spartanfire            | 0.08                      | spartanfire-0.08.jar                                      | None                                     |
       | LCH   | spartanshields         | 1.5.4                     | SpartanShields-1.12.2-1.5.4.jar                           | None                                     |
       | LCH   | stg                    | 1.12.2-1.2.3              | stg-1.12.2-1.2.3.jar                                      | None                                     |
       | LCH   | storagedrawers         | 5.2.2                     | StorageDrawers-1.12.2-5.4.2.jar                           | None                                     |
       | LCH   | strawgolem             | 1.3                       | strawgolem-1.4.1.jar                                      | None                                     |
       | LCH   | subterraneanswitcheroo | 1.1.0                     | SubSwitch1.1.0.jar                                        | None                                     |
       | LCH   | tfspellpack            | 1.0.1                     | TFSpellPack-1.0.1-MC1.12.2.jar                            | None                                     |
       | LCH   | thesummoner            | 1.0.1-beta                | thesummoner-1.0.1.jar                                     | None                                     |
       | LCH   | tinkersaether          | 1.3.0                     | tinkersaether-1.3.0.jar                                   | None                                     |
       | LCH   | tcomplement            | 1.12.2-0.4.3              | TinkersComplement-1.12.2-0.4.3.jar                        | None                                     |
       | LCH   | tinkersjei             | 1.2                       | tinkersjei-1.2.jar                                        | None                                     |
       | LCH   | tinkertoolleveling     | 1.12.2-1.1.0.DEV.b23e769  | TinkerToolLeveling-1.12.2-1.1.0.jar                       | None                                     |
       | LCH   | torchmaster            | 1.8.1.81                  | torchmaster_1.12.2-1.8.1.81.jar                           | 5e9a436b366831c8f54a7e80b015784da69278c6 |
       | LCH   | tropicraft             | 7.1.9.115                 | tropicraft-MC1.12.2-7.1.9.115.jar                         | None                                     |
       | LCH   | uniquee                | 1.9.0                     | Unique+Enchantments+V1.12.2-1.9.jar                       | None                                     |
       | LCH   | uppers                 | 0.0.6                     | Uppers-0.0.6.jar                                          | None                                     |
       | LCH   | vanillafix             | 1.0.10-150                | VanillaFix-1.0.10-150.jar                                 | None                                     |
       | LCH   | waddles                | 0.6.0                     | Waddles-1.12.2-0.6.0.jar                                  | None                                     |
       | LCH   | wailaharvestability    | 1.1.12                    | WailaHarvestability-mc1.12-1.1.12.jar                     | None                                     |
       | LCH   | wawla                  | 2.6.275                   | Wawla-1.12.2-2.6.275.jar                                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | waystones              | 4.1.0                     | Waystones_1.12.2-4.1.0.jar                                | None                                     |
       | LCH   | wolfarmor              | 3.4.1.1                   | wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar             | None                                     |
       | LCH   | xlfoodmod              | 1.12.2-1.9.2              | XL-Food-Mod-1.12.2-1.9.2.jar                              | None                                     |
       | LCH   | xpbook                 | v1.1.4                    | xptome-1.12.2-v1.1.4.jar                                  | None                                     |
       | LCH   | immersiveengineering   | 0.12-92                   | ImmersiveEngineering-0.12-92.jar                          | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | LCH   | thebetweenlands        | 3.6.0                     | TheBetweenlands-3.6.0-universal.jar                       | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LCH   | totemexpansion         | 1.2.2                     | totemexpansion-1.2.2-1.12.2.jar                           | None                                     |
       | LCH   | adfinders              | 1.12.2-2.3.14.0           | AdFinders-1.12.2-2.3.14.0-build.0501.jar                  | None                                     |
       | LCH   | mysticallib            | 1.12.2-1.7.0              | mysticallib-1.12.2-1.7.0.jar                              | None                                     |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      AstralCore (astralsorcery-1.12.2-1.10.23.jar)
                                        
                                      CorePlugin (ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar)
                                        
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.0-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      iceandfire (iceandfire-1.9.1-1.12.2.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      WolfArmorCore (wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar)
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce RTX 2070/PCIe/SSE2'
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - quarkIntegration (Enabled/Not Forced)
  Pulsar/tcomplement loaded Pulses: - ModuleCommons (Enabled/Forced)
                                    - ModuleMelter (Enabled/Not Forced)
                                    - ModuleArmor (Enabled/Not Forced)
                                    - ModuleSteelworks (Enabled/Not Forced)
                                    - ChiselPlugin (Enabled/Not Forced)
                                    - ToolLevelingPlugin (Enabled/Not Forced)
                                    - Oredict (Enabled/Forced)
  Suspected Mods: AutoRegLib (autoreglib)
  Launched Version: forge-14.23.5.2854
  LWJGL: 2.9.4
  OpenGL: GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 16x AMD Ryzen 7 2700 Eight-Core Processor

**Comment by lamoyrl90** [comment]
Install Just Enough IDs: https://www.curseforge.com/minecraft/mc-mods/jeid

You reached the ID limit for blocks, JEID removes this limit.
